
# Configuracion global
spring.application.name=api-auth
server.servlet.context-path=/api/v1

# Configuracion de conexion de base de datos.
spring.datasource.url=jdbc:postgresql://localhost:5432/api-auth
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de hibernate y debug.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT
jwt.secret=dGVzdC1zZWNyZXQtZm9yLWFwaS1hdXRoLWFwcGxpY2F0aW9uLXNlY3VyZS1rZXktMjU2Yml0cw==
jwt.expiration=86400000